/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sknm;


import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.text.Format;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jacek Cierpka
 */
public class OknoBazy extends javax.swing.JFrame {

    /**
     * Creates new form OknoBazy
     */
    public OknoBazy() {
        initComponents();
        getConnection();
        Wyswietl_Rekordy();
    }
    
    String plikPath = null;
    int pozycja = 0;
    
    public Connection getConnection(){
    
            Connection polaczenie=null;
        try {
          // polaczenie= DriverManager.getConnection("jdbc:mysql://localhost/playlista2","root","");
          polaczenie= DriverManager.getConnection("jdbc:mysql://localhost/playlista3","root","");
            JOptionPane.showMessageDialog(null, "Polaczono");
            return polaczenie;
        } catch (SQLException ex) {
            Logger.getLogger(OknoBazy.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Odrzucono Polaczenie");
            return null;
        }
            
    }
    
   /* public sciezkaPliku(String plikPath){
    
    }*/
    
    public boolean plikiWej(){
        if (pole_artysta.getText()==null || pole_utwor.getText()==null || pole_tempo.getText()==null || pole_dlugosc==null){return false;}
        else{
            try{
                Float.parseFloat(pole_utwor.getText());
                return true;
            }catch(Exception ex){
                return false;
            }
        }
    }
    
      public ArrayList<Baza> pobierzPlayliste()
    {
            ArrayList<Baza> listaPlaylisty  = new ArrayList<Baza>();
            Connection polaczenie = getConnection();
            String pytanie = "SELECT * FROM playlista";
            
            Statement st;
            ResultSet rs;
            
        try {
            
            st = polaczenie.createStatement();
            rs = st.executeQuery(pytanie);
            Baza playlista;
            
            while(rs.next())
            {
                playlista = new Baza(rs.getInt("Id_Na_Playliscie"),rs.getString("Nazwa_Artysty"),rs.getString("Nazwa_Utworu"),rs.getString("Lokalizacja_pliku"),rs.getString("Dlugosc_Utworu"),rs.getString("Tempo"));
                listaPlaylisty.add(playlista);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(OknoBazy.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return  listaPlaylisty; 
                
    }
      
    public void Wyswietl_Rekordy()
    {
        ArrayList<Baza> lista = pobierzPlayliste();
        DefaultTableModel model = (DefaultTableModel)zawartosc_tabeli.getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[6];
        for(int i = 0; i < lista.size(); i++)
        {
            row[0] = lista.get(i).getId_Playlisty();
            row[1] = lista.get(i).getNazwa_Artysty();
            row[2] = lista.get(i).getNazwa_Utworu();
            row[3] = lista.get(i).getDlugosc();
            row[4] = lista.get(i).getTempo();
            row[5] = lista.get(i).getLokalizacja_Utworu();
            model.addRow(row);
        }
    
    }  
    public void Wyswietl_Zawartosc(int index)
    {
            pole_nr.setText(Integer.toString(pobierzPlayliste().get(index).getId_Playlisty()));
            pole_artysta.setText(pobierzPlayliste().get(index).getNazwa_Artysty());
            pole_utwor.setText(pobierzPlayliste().get(index).getNazwa_Utworu());
            pole_dlugosc.setText(pobierzPlayliste().get(index).getDlugosc());
            pole_tempo.setText(pobierzPlayliste().get(index).getTempo());
            pokaz_adres.setText(pobierzPlayliste().get(index).getLokalizacja_Utworu());
    }        
           /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pole_nr = new javax.swing.JTextField();
        pole_artysta = new javax.swing.JTextField();
        pole_utwor = new javax.swing.JTextField();
        pole_tempo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        zawartosc_tabeli = new javax.swing.JTable();
        guz_Adres_pliku = new javax.swing.JButton();
        guz_edytuj = new javax.swing.JButton();
        guz_usun = new javax.swing.JButton();
        guz_nastepny = new javax.swing.JButton();
        guz_pierwszy = new javax.swing.JButton();
        guz_poprzedni = new javax.swing.JButton();
        guz_ostatni = new javax.swing.JButton();
        pole_dlugosc = new javax.swing.JTextField();
        pokaz_adres = new java.awt.Label();
        guz_Dodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Numer Pozycji:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Artysta:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Utwor:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Tempo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Dlugosc:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Adres Pliku:");

        pole_nr.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pole_nr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pole_nrActionPerformed(evt);
            }
        });

        pole_artysta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pole_artysta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pole_artystaActionPerformed(evt);
            }
        });

        pole_utwor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pole_utwor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pole_utworActionPerformed(evt);
            }
        });

        pole_tempo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pole_tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pole_tempoActionPerformed(evt);
            }
        });

        zawartosc_tabeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "Artysta", "Utwor", "Dlugosc", "Tempo", "Adres Pliku"
            }
        ));
        zawartosc_tabeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zawartosc_tabeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(zawartosc_tabeli);
        if (zawartosc_tabeli.getColumnModel().getColumnCount() > 0) {
            zawartosc_tabeli.getColumnModel().getColumn(0).setMinWidth(50);
            zawartosc_tabeli.getColumnModel().getColumn(0).setPreferredWidth(50);
            zawartosc_tabeli.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        guz_Adres_pliku.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        guz_Adres_pliku.setText("Adres");
        guz_Adres_pliku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guz_Adres_plikuActionPerformed(evt);
            }
        });

        guz_edytuj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guz_edytuj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikony/icons/Refresh-icon.png"))); // NOI18N
        guz_edytuj.setText("Edytuj");
        guz_edytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guz_edytujActionPerformed(evt);
            }
        });

        guz_usun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guz_usun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikony/icons/Remove-icon (1).png"))); // NOI18N
        guz_usun.setText("Usun");
        guz_usun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guz_usunActionPerformed(evt);
            }
        });

        guz_nastepny.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guz_nastepny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikony/icons/forward-icon (1).png"))); // NOI18N
        guz_nastepny.setText("Nastepny");
        guz_nastepny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guz_nastepnyActionPerformed(evt);
            }
        });

        guz_pierwszy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guz_pierwszy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikony/icons/first-track-icon (1).png"))); // NOI18N
        guz_pierwszy.setText("Pierwszy");
        guz_pierwszy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guz_pierwszyActionPerformed(evt);
            }
        });

        guz_poprzedni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guz_poprzedni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikony/icons/rewind-icon (1).png"))); // NOI18N
        guz_poprzedni.setText("Poprzedni");
        guz_poprzedni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guz_poprzedniActionPerformed(evt);
            }
        });

        guz_ostatni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guz_ostatni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikony/icons/last-track-icon (1).png"))); // NOI18N
        guz_ostatni.setText("Ostatni");
        guz_ostatni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guz_ostatniActionPerformed(evt);
            }
        });

        pole_dlugosc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        pokaz_adres.setBackground(new java.awt.Color(255, 255, 255));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, guz_Adres_pliku, org.jdesktop.beansbinding.ELProperty.create("${text}"), pokaz_adres, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        guz_Dodaj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guz_Dodaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikony/icons/Add-icon (1).png"))); // NOI18N
        guz_Dodaj.setText("Dodaj");
        guz_Dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guz_DodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pole_artysta)
                            .addComponent(pole_nr)
                            .addComponent(pole_utwor)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pole_tempo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pole_dlugosc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 546, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(guz_Adres_pliku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pokaz_adres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guz_edytuj, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(guz_usun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guz_nastepny, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guz_pierwszy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guz_poprzedni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guz_ostatni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guz_Dodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pole_nr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pole_artysta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pole_utwor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pole_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pole_dlugosc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(guz_Adres_pliku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pokaz_adres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guz_Dodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guz_edytuj, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guz_usun, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guz_pierwszy, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guz_nastepny, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guz_poprzedni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guz_ostatni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pole_nrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pole_nrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pole_nrActionPerformed

    private void pole_artystaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pole_artystaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pole_artystaActionPerformed

    private void pole_utworActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pole_utworActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pole_utworActionPerformed

    private void pole_tempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pole_tempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pole_tempoActionPerformed

    private void guz_Adres_plikuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guz_Adres_plikuActionPerformed
        JFileChooser file=new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.muzyka", "mp3","wma");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String sciezka = selectedFile.getAbsolutePath();
            plikPath=sciezka;
            pokaz_adres.setText(plikPath);
        }
        else{
            System.out.println("Nie wybrano pliku");
        }
    }//GEN-LAST:event_guz_Adres_plikuActionPerformed

    private void guz_DodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guz_DodajActionPerformed
       System.out.println("sciezka: "+plikPath);
        if ( plikPath != null){
            Connection polaczenie=getConnection();
            System.out.println("weszlo");
            /*
                   try {PreparedStatement ps= polaczenie.prepareStatement("INSERT INTO artysta(Nazwa_Artysty) VALUES(?)");
                       ps.setString(1, pole_artysta.getText());
                       ps.executeUpdate();
                       
                   } catch (SQLException ex) {
                       Logger.getLogger(OknoBazy.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   try {PreparedStatement ps= polaczenie.prepareStatement("INSERT INTO tempo(Tempo) VALUES(?)");
                       ps.setString(1, pole_tempo.getText());
                       ps.executeUpdate();
                   } catch (SQLException ex) {
                       Logger.getLogger(OknoBazy.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   try {PreparedStatement ps= polaczenie.prepareStatement("INSERT INTO utwor(Nazwa_Utworu,Dlugosc_Utworu,Lokalizacja_pliku) VALUES(?,?,?)");
                       ps.setString(1, pole_utwor.getText());
                       ps.setString(2, pole_dlugosc.getText());
                       ps.setString(3, plikPath);
                       ps.executeUpdate();
                   } catch (SQLException ex) {
                       Logger.getLogger(OknoBazy.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   
                   try {
               
               PreparedStatement ps= polaczenie.prepareStatement("INSERT INTO playlista(id_Na_Playliscie,Nazwa_Artysty,Nazwa_Utworu,Lokalizacja_pliku, Dlugosc_Utworu, Tempo) VALUES(?,?,?,?,?,?)");
               ps.setString(1, pole_nr.getText()); 
               ps.setString(2, pole_artysta.getText());
                 ps.setString(3, pole_utwor.getText());
                 ps.setString(4, plikPath);
                 ps.setString(5, pole_dlugosc.getText());
                ps.setString(6, pole_tempo.getText());
                ps.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(OknoBazy.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            
            try {
               
               PreparedStatement ps= polaczenie.prepareStatement("INSERT INTO playlista(Nazwa_Artysty,Nazwa_Utworu,Lokalizacja_pliku, Dlugosc_Utworu, Tempo)"+"values(?,?,?,?,?)");
                ps.setString(1, pole_artysta.getText());
                 ps.setString(2, pole_utwor.getText());
                 ps.setString(3, plikPath);
                 ps.setString(4, pole_dlugosc.getText());
                ps.setString(5, pole_tempo.getText());
                ps.executeUpdate();
               
                JOptionPane.showMessageDialog(null,"Dodano nowa zawartosc" );
            } catch (SQLException ex) {
                Logger.getLogger(OknoBazy.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            }else{
                   JOptionPane.showMessageDialog(null,"Jedno lub wiecej pol jest puste" );
                }
            System.out.println("art: "+pole_artysta.getText());
            System.out.println("utw: "+pole_utwor.getText());
            System.out.println("temp: "+pole_tempo.getText());
            System.out.println("dlug: "+pole_dlugosc.getText());
            System.out.println("sciezka: "+plikPath);
    }//GEN-LAST:event_guz_DodajActionPerformed

    private void guz_edytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guz_edytujActionPerformed
        
        if(pole_nr != null){
            String OdswiezPytanie = null;
            PreparedStatement ps = null;
            Connection polaczenie = getConnection();
          
                 
                try { 
                    OdswiezPytanie= "UPDATE playlista SET Nazwa_Artysty=?, Nazwa_Utworu=?, Lokalizacja_pliku=?, Dlugosc_Utworu=?, Tempo=? WHERE Id_Na_Playliscie=?";
                    ps = polaczenie.prepareStatement(OdswiezPytanie);
                    
                     ps.setString(1, pole_artysta.getText());
                     ps.setString(2, pole_utwor.getText());
                     ps.setString(3, plikPath);
                     ps.setString(4, pole_dlugosc.getText());
                     ps.setString(5, pole_tempo.getText());
                     ps.setInt(6, Integer.parseInt(pole_nr.getText()));
                     ps.executeUpdate();
                } catch (SQLException ex) {
                    Logger.getLogger(OknoBazy.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{JOptionPane.showMessageDialog(null, "Jedno lub wiecej pol jest puste");}
                
           
        
       
    }//GEN-LAST:event_guz_edytujActionPerformed

    private void guz_usunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guz_usunActionPerformed
        
        if(!pole_nr.getText().equals("")){
            try {
                Connection polaczenie = getConnection();
                PreparedStatement ps = polaczenie.prepareStatement("DELETE FROM playlista WHERE Id_Na_Playliscie=?");
                int id = Integer.parseInt(pole_nr.getText());
                ps.setInt(1,id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Usunieto pozycje");
            } catch (SQLException ex) {
                Logger.getLogger(OknoBazy.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Nie udalo sie usunac pozycji");
            }
        }else{JOptionPane.showMessageDialog(null, "Nie udalo sie usunac pozycji. Prosze podac id utworu  ");}
    }//GEN-LAST:event_guz_usunActionPerformed

    private void zawartosc_tabeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zawartosc_tabeliMouseClicked
        int index = zawartosc_tabeli.getSelectedRow();
        Wyswietl_Zawartosc(index);
    }//GEN-LAST:event_zawartosc_tabeliMouseClicked

    private void guz_pierwszyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guz_pierwszyActionPerformed
         pozycja = 0;
        Wyswietl_Zawartosc(pozycja);
    }//GEN-LAST:event_guz_pierwszyActionPerformed

    private void guz_ostatniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guz_ostatniActionPerformed
        pozycja = pobierzPlayliste().size()-1;
        Wyswietl_Zawartosc(pozycja);
    }//GEN-LAST:event_guz_ostatniActionPerformed

    private void guz_poprzedniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guz_poprzedniActionPerformed
        pozycja--;
        if(pozycja < 0){ pozycja= 0;}
        Wyswietl_Zawartosc(pozycja);
    }//GEN-LAST:event_guz_poprzedniActionPerformed

    private void guz_nastepnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guz_nastepnyActionPerformed
         pozycja++;
         if (pozycja >= pobierzPlayliste().size())
         {pozycja = pobierzPlayliste().size()-1;}
         Wyswietl_Zawartosc(pozycja);  
        
        
        
    }//GEN-LAST:event_guz_nastepnyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoBazy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoBazy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoBazy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoBazy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoBazy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guz_Adres_pliku;
    private javax.swing.JButton guz_Dodaj;
    private javax.swing.JButton guz_edytuj;
    private javax.swing.JButton guz_nastepny;
    private javax.swing.JButton guz_ostatni;
    private javax.swing.JButton guz_pierwszy;
    private javax.swing.JButton guz_poprzedni;
    private javax.swing.JButton guz_usun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label pokaz_adres;
    private javax.swing.JTextField pole_artysta;
    private javax.swing.JTextField pole_dlugosc;
    private javax.swing.JTextField pole_nr;
    private javax.swing.JTextField pole_tempo;
    private javax.swing.JTextField pole_utwor;
    private javax.swing.JTable zawartosc_tabeli;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
